server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  #时间格式设置
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #数据库配置
  datasource:
    druid:
      driverClassName: "com.mysql.cj.jdbc.Driver"
      url: "jdbc:mysql://localhost:3306/V1_1_0__init_table?serverTimezone=Hongkong&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false  # serverTimezone=Hongkong 需要填上时区" #k8s env
      username: "root" #k8s env
      password: "root" #k8s env
      initialSize: 1
      minIdle: 3
      maxActive: 20
      transaction-query-timeout: 20
      filters: stat,wall,slf4j
      stat-view-servlet:
        url-pattern: "/druid/*"
      filter:
        stat:
          db-type: mysql
      db-type: mysql
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      time-between-eviction-runs-millis: 60000
      max-wait: 30000
      min-evictable-idle-time-millis: 300000
  #redis配置
  redis:
    host:
    port:
    password:
    database:
    timeOut: 60000


#mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bike.ztd.entity
  check-config-location: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 0
      #逻辑未删除值
      logic-not-delete-value: 1

swagger:
  show: true

aliyun:
  sms:
    code: ""
    sign: ""
    accessKeySecret:
    accessKeyId:
  oss:
    bucketName:
    accessKeySecret:
    accessKeyId:
    #Endpoint按实际情况填写。
    endpoint: oss-cn-beijing.aliyuncs.com

#token有效期毫秒为单位
token:
  # 3600000
  expire: 3600000

password:
  wrong:
    expire: 300000
    times: 3

